=== doms99/OR/public/schema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "http://example.com/example.json",
  "type": "array",
  "default": [],
  "title": "Winning F1 car by season",
  "items": {
      "type": "object",
      "title": "F1 Car",
      "description": "Winning car of the season of F1",
      "required": [
          "id",
          "team",
          "year",
          "engine_regulation",
          "length",
          "width",
          "height",
          "weight",
          "tyre"
      ],
      "properties": {
          "id": {
              "type": "string",
              "title": "Car id",
              "description": "Unique car id"
          },
          "team": {
              "type": "string",
              "title": "Winning team name",
              "description": "Winning team name"

          },
          "year": {
              "type": "string",
              "title": "Season year",
              "description": "Year the season was held in"
          },
          "engine_regulation": {
              "type": "object",
              "title": "Engine regulation",
              "description": "Engine regulation winning car was built by",
              "required": [
                  "id",
                  "years",
                  "induction",
                  "number_of_pistons",
                  "layout",
                  "bank_angle",
                  "max_displacement",
                  "rev_limit"
              ],
              "properties": {
                  "id": {
                      "type": "string",
                      "title": "Car id",
                      "description": "Unique engine regulation id"
                  },
                  "years": {
                      "type": "array",
                      "title": "Active years",
                      "description": "Years regulation was active in",
                      "items": {
                          "type": "string",
                          "title": "Years"
                      }

                  },
                  "induction": {
                      "type": "array",
                      "title": "Engine induction",
                      "description": "Induction method engine were allowed to use",
                      "items": {
                          "type": "string",
                          "title": "Induction method"
                      }

                  },
                  "number_of_pistons": {
                      "type": "integer",
                      "title": "Number of pistons",
                      "description": "Number of pistons engines were allowed to have"

                  },
                  "layout": {
                      "type": "string",
                      "title": "Engine layout",
                      "description": "Allowed engine layout"

                  },
                  "bank_angle": {
                      "type": [
                          "number",
                          "null"
                      ],
                      "title": "Engine bank angle",
                      "description": "Allowed engine bank angle"

                  },
                  "max_displacement": {
                      "type": "array",
                      "title": "Engine max displacement",
                      "description": "Maximum allowed displacement of the engine",
                      "items": {
                          "type": "number",
                          "title": "F1 Car Schema"

                      }

                  },
                  "rev_limit": {
                      "type": [
                          "integer",
                          "null"
                      ],
                      "title": "Rev limit",
                      "description": "Engine RMP limit"
                  }
              }
          },
          "length": {
              "type": [
                  "number",
                  "null"
              ],
              "title": "Car length",
              "description": "Car length"
          },
          "width": {
              "type": [
                  "number",
                  "null"
              ],
              "title": "Car width",
              "description": "Car width"
          },
          "height": {
              "type": [
                  "number",
                  "null"
              ],
              "title": "Car height",
              "description": "Car height"
          },
          "weight": {
              "type": [
                  "number",
                  "null"
              ],
              "title": "Car weight",
              "description": "Car weight"
          },
          "tyre": {
              "type": "string",
              "title": "Tyre manufacturer",
              "description": "Tyre manufacturer winning car used"
          }
      }
  }
}

=== doms99/OR/f1_winning_cars_by_year.json
[
  {
    "id": "7b7a53e239400a13bd6be6c91c4f6c4e",
    "team": "Mercedes",
    "year": "2020",
    "engine_regulation": {
      "id": "02584497de1106df06fbae4be54fcfef",
      "years": ["2014","2015","2016","2017","2018","2019","2020","2021"],
      "induction": ["natural","forced"],
      "number_of_pistons": 6,
      "layout": "V",
      "bank_angle": 90.00,
      "max_displacement": [1.6,1.6],
      "rev_limit": 15000
    },
    "length": 5000.0,
    "width": 2000.0,
    "height": 950.0,
    "weight": 746.0,
    "tyre": "Pirelli"
  },
  {
    "id": "ea6b2efbdd4255a9f1b3bbc6399b58f4",
    "team": "Mercedes",
    "year": "2019",
    "engine_regulation": {
      "id": "02584497de1106df06fbae4be54fcfef",
      "years": ["2014","2015","2016","2017","2018","2019","2020","2021"],
      "induction": ["natural","forced"],
      "number_of_pistons": 6,
      "layout": "V",
      "bank_angle": 90.00,
      "max_displacement": [1.6,1.6],
      "rev_limit": 15000
    },
    "length": 5000.0,
    "width": 2000.0,
    "height": 950.0,
    "weight": 746.0,
    "tyre": "Pirelli"
  },
  {
    "id": "84ddfb34126fc3a48ee38d7044e87276",
    "team": "Mercedes",
    "year": "2018",
    "engine_regulation": {
      "id": "02584497de1106df06fbae4be54fcfef",
      "years": ["2014","2015","2016","2017","2018","2019","2020","2021"],
      "induction": ["natural","forced"],
      "number_of_pistons": 6,
      "layout": "V",
      "bank_angle": 90.00,
      "max_displacement": [1.6,1.6],
      "rev_limit": 15000
    },
    "length": null,
    "width": null,
    "height": null,
    "weight": null,
    "tyre": "Pirelli"
  },
  {
    "id": "8d8818c8e140c64c743113f563cf750f",
    "team": "Mercedes",
    "year": "2017",
    "engine_regulation": {
      "id": "02584497de1106df06fbae4be54fcfef",
      "years": ["2014","2015","2016","2017","2018","2019","2020","2021"],
      "induction": ["natural","forced"],
      "number_of_pistons": 6,
      "layout": "V",
      "bank_angle": 90.00,
      "max_displacement": [1.6,1.6],
      "rev_limit": 15000
    },
    "length": null,
    "width": null,
    "height": null,
    "weight": null,
    "tyre": "Pirelli"
  },
  {
    "id": "95192c98732387165bf8e396c0f2dad2",
    "team": "Mercedes",
    "year": "2016",
    "engine_regulation": {
      "id": "02584497de1106df06fbae4be54fcfef",
      "years": ["2014","2015","2016","2017","2018","2019","2020","2021"],
      "induction": ["natural","forced"],
      "number_of_pistons": 6,
      "layout": "V",
      "bank_angle": 90.00,
      "max_displacement": [1.6,1.6],
      "rev_limit": 15000
    },
    "length": null,
    "width": null,
    "height": null,
    "weight": null,
    "tyre": "Pirelli"
  },
  {
    "id": "65d2ea03425887a717c435081cfc5dbb",
    "team": "Mercedes",
    "year": "2015",
    "engine_regulation": {
      "id": "02584497de1106df06fbae4be54fcfef",
      "years": ["2014","2015","2016","2017","2018","2019","2020","2021"],
      "induction": ["natural","forced"],
      "number_of_pistons": 6,
      "layout": "V",
      "bank_angle": 90.00,
      "max_displacement": [1.6,1.6],
      "rev_limit": 15000
    },
    "length": 5000.0,
    "width": 1800.0,
    "height": 950.0,
    "weight": 702.0,
    "tyre": "Pirelli"
  },
  {
    "id": "cee8d6b7ce52554fd70354e37bbf44a2",
    "team": "Mercedes",
    "year": "2014",
    "engine_regulation": {
      "id": "02584497de1106df06fbae4be54fcfef",
      "years": ["2014","2015","2016","2017","2018","2019","2020","2021"],
      "induction": ["natural","forced"],
      "number_of_pistons": 6,
      "layout": "V",
      "bank_angle": 90.00,
      "max_displacement": [1.6,1.6],
      "rev_limit": 15000
    },
    "length": 4800.0,
    "width": 2000.0,
    "height": 950.0,
    "weight": 691.0,
    "tyre": "Pirelli"
  },
  {
    "id": "8038da89e49ac5eabb489cfc6cea9fc1",
    "team": "RedBull",
    "year": "2013",
    "engine_regulation": {
      "id": "7278ac6d56887e475fda86802c5b36a1",
      "years": ["2009","2010","2011","2012","2013"],
      "induction": ["natural"],
      "number_of_pistons": 8,
      "layout": "V",
      "bank_angle": 90.00,
      "max_displacement": [2.4],
      "rev_limit": 18000
    },
    "length": null,
    "width": null,
    "height": null,
    "weight": null,
    "tyre": "Pirelli"
  },
  {
    "id": "253614bbac999b38b5b60cae531c4969",
    "team": "RedBull",
    "year": "2012",
    "engine_regulation": {
      "id": "7278ac6d56887e475fda86802c5b36a1",
      "years": ["2009","2010","2011","2012","2013"],
      "induction": ["natural"],
      "number_of_pistons": 8,
      "layout": "V",
      "bank_angle": 90.00,
      "max_displacement": [2.4],
      "rev_limit": 18000
    },
    "length": null,
    "width": null,
    "height": null,
    "weight": null,
    "tyre": "Pirelli"
  },
  {
    "id": "c8758b517083196f05ac29810b924aca",
    "team": "RedBull",
    "year": "2011",
    "engine_regulation": {
      "id": "7278ac6d56887e475fda86802c5b36a1",
      "years": ["2009","2010","2011","2012","2013"],
      "induction": ["natural"],
      "number_of_pistons": 8,
      "layout": "V",
      "bank_angle": 90.00,
      "max_displacement": [2.4],
      "rev_limit": 18000
    },
    "length": null,
    "width": null,
    "height": null,
    "weight": null,
    "tyre": "Pirelli"
  },
  {
    "id": "d7a84628c025d30f7b2c52c958767e76",
    "team": "RedBull",
    "year": "2010",
    "engine_regulation": {
      "id": "7278ac6d56887e475fda86802c5b36a1",
      "years": ["2009","2010","2011","2012","2013"],
      "induction": ["natural"],
      "number_of_pistons": 8,
      "layout": "V",
      "bank_angle": 90.00,
      "max_displacement": [2.4],
      "rev_limit": 18000
    },
    "length": null,
    "width": null,
    "height": null,
    "weight": null,
    "tyre": "Bridgestone"
  },
  {
    "id": "f1981e4bd8a0d6d8462016d2fc6276b3",
    "team": "Brawn",
    "year": "2009",
    "engine_regulation": {
      "id": "7278ac6d56887e475fda86802c5b36a1",
      "years": ["2009","2010","2011","2012","2013"],
      "induction": ["natural"],
      "number_of_pistons": 8,
      "layout": "V",
      "bank_angle": 90.00,
      "max_displacement": [2.4],
      "rev_limit": 18000
    },
    "length": 4700.0,
    "width": 1800.0,
    "height": 950.0,
    "weight": null,
    "tyre": "Bridgestone"
  },
  {
    "id": "ef8446f35513a8d6aa2308357a268a7e",
    "team": "McLaren",
    "year": "2008",
    "engine_regulation": {
      "id": "1d7b378c6f36b418168978807390b335",
      "years": ["2007","2008"],
      "induction": ["natural"],
      "number_of_pistons": 8,
      "layout": "V",
      "bank_angle": 90.00,
      "max_displacement": [2.4],
      "rev_limit": 19000
    },
    "length": null,
    "width": null,
    "height": null,
    "weight": null,
    "tyre": "Bridgestone"
  },
  {
    "id": "a00e5eb0973d24649a4a920fc53d9564",
    "team": "Ferrari",
    "year": "2007",
    "engine_regulation": {
      "id": "7278ac6d56887e475fda86802c5b36a1",
      "years": ["2009","2010","2011","2012","2013"],
      "induction": ["natural"],
      "number_of_pistons": 8,
      "layout": "V",
      "bank_angle": 90.00,
      "max_displacement": [2.4],
      "rev_limit": 18000
    },
    "length": 4545.0,
    "width": 1796.0,
    "height": 959.0,
    "weight": 600.0,
    "tyre": "Bridgestone"
  },
  {
    "id": "ea5a486c712a91e48443cd802642223d",
    "team": "Renault",
    "year": "2006",
    "engine_regulation": {
      "id": "a43a418fe0720efde1437cc91474e9e8",
      "years": ["2006"],
      "induction": ["natural"],
      "number_of_pistons": 8,
      "layout": "V",
      "bank_angle": 90.00,
      "max_displacement": [2.4],
      "rev_limit": null
    },
    "length": 4800.0,
    "width": 1800.0,
    "height": 950.0,
    "weight": 600.0,
    "tyre": "Michelin"
  },
  {
    "id": "d47268e9db2e9aa3827bba3afb7ff94a",
    "team": "Renault",
    "year": "2005",
    "engine_regulation": {
      "id": "65ff168b9d8281dc8405d78f27b9a2b1",
      "years": ["2000","2001","2002","2003","2004","2005"],
      "induction": ["natural"],
      "number_of_pistons": 10,
      "layout": "V",
      "bank_angle": null,
      "max_displacement": [3.0],
      "rev_limit": null
    },
    "length": 4800.0,
    "width": 1800.0,
    "height": 950.0,
    "weight": 605.0,
    "tyre": "Michelin"
  },
  {
    "id": "b8b4b727d6f5d1b61fff7be687f7970f",
    "team": "Ferrari",
    "year": "2004",
    "engine_regulation": {
      "id": "65ff168b9d8281dc8405d78f27b9a2b1",
      "years": ["2000","2001","2002","2003","2004","2005"],
      "induction": ["natural"],
      "number_of_pistons": 10,
      "layout": "V",
      "bank_angle": null,
      "max_displacement": [3.0],
      "rev_limit": null
    },
    "length": 4545.0,
    "width": 1796.0,
    "height": 959.0,
    "weight": 605.0,
    "tyre": "Bridgestone"
  },
  {
    "id": "a591024321c5e2bdbd23ed35f0574dde",
    "team": "Ferrari",
    "year": "2003",
    "engine_regulation": {
      "id": "65ff168b9d8281dc8405d78f27b9a2b1",
      "years": ["2000","2001","2002","2003","2004","2005"],
      "induction": ["natural"],
      "number_of_pistons": 10,
      "layout": "V",
      "bank_angle": null,
      "max_displacement": [3.0],
      "rev_limit": null
    },
    "length": 4545.0,
    "width": 1796.0,
    "height": 959.0,
    "weight": null,
    "tyre": "Bridgestone"
  },
  {
    "id": "4ba29b9f9e5732ed33761840f4ba6c53",
    "team": "Ferrari",
    "year": "2002",
    "engine_regulation": {
      "id": "65ff168b9d8281dc8405d78f27b9a2b1",
      "years": ["2000","2001","2002","2003","2004","2005"],
      "induction": ["natural"],
      "number_of_pistons": 10,
      "layout": "V",
      "bank_angle": null,
      "max_displacement": [3.0],
      "rev_limit": null
    },
    "length": 4495.0,
    "width": 1796.0,
    "height": 959.0,
    "weight": null,
    "tyre": "Bridgestone"
  },
  {
    "id": "d0fb963ff976f9c37fc81fe03c21ea7b",
    "team": "Ferrari",
    "year": "2001",
    "engine_regulation": {
